name: hack2020
description: A new Flutter project.

sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  shared_preferences: ^0.5.6+3
  equatable: ^1.1.1
  rxdart: ^0.23.1
  cupertino_icons: ^0.1.3
  lottie: ^0.3.2
  provider: ^4.0.4
  toast: ^0.1.5
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  carousel_slider: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.10.9
  build_runner: 1.10.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

